### ISSUE TITLE
[0.2.7] Search Bar

### ISSUE THREAD

**Issue by Pri-Dave** [BeanPlant/BeanPlant-Chat#17]
The search bar has to be 'backspaced' before you can type, or you type and you have 'Search...' in your actual search. It should be made like the message one, ''Type a message''

**Comment by the-DJDJ** [comment]
Fixed in 895ca4394b288f409f5434611c93023551836ea7

**Comment by the-DJDJ** [comment]
Fixed in 895ca4394b288f409f5434611c93023551836ea7

**Comment by the-DJDJ** [comment]
Fixed in 895ca4394b288f409f5434611c93023551836ea7
